config/routes.rb
Rails.application.routes.draw do
  resource :session

  get 'signin' => 'sessions#new'

  get 'signup' => 'users#new'

  resources :users

  resources :projects do
  	resources :pledges
  end

  root "projects#index"
  	resources :projects
end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  belongs_to :project

  validates :name, :email, presence: true

  validates :email, format: { with: /(\S+)@(\S+)/ }
  
  AMOUNT_LEVELS = [25.00, 50.00, 100.00, 200.00, 500.00]

  validates :amount, inclusion: { in: AMOUNT_LEVELS }
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates_presence_of :name, :description

  validates_length_of :description, maximum: 500

  validates_numericality_of :target_pledge_amount, greater_than: 0

  validates_format_of :website,
      with: /https?:\/\/[\S]+\b/i,
      message: "must reference a valid URL"

  validates_format_of :image_file_name,
      with: /\w+\.(gif|jpg|png)\z/i,
      message: "must reference a GIF, JPG, or PNG image"

  has_many :pledges, dependent: :destroy

  def self.accepting_pledges
    where("pledging_ends_on >= ?", Time.now).order("pledging_ends_on asc")
  end

  def pledging_expired?
    pledging_ends_on < Date.today
  end

  def total_amount_pledged
    pledges.sum(:amount) || 0
  end

  def amount_outstanding
    target_pledge_amount - total_amount_pledged
  end

  def funded?
    amount_outstanding <= 0
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :name, presence: true

  validates :email, presence: true,                   
                    format: /\A\S+@\S+\z/,
                    uniqueness: { case_sensitive: false }

  validates :password, length: {minimum: 4, allow_blank: true }

  validates :username, presence: true,
  						format: /\A[A-Z0-9]+\z/i,
  						uniqueness: { case_sensitive: false }

	def gravatar_id
	  Digest::MD5::hexdigest(email.downcase)
	end

	def self.authenticate(email, password)
	  user = User.find_by(email: email)
	  user && user.authenticate(password)
	end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def require_signin
  	unless current_user
  		session[:intended_url] = request.url
  		redirect_to new_session_url, alert: "Please sign in first!"
  	end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  helper_method :current_user
  
  def current_user?(user)
    current_user == user
  end

  helper_method :current_user?

end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
  before_action :set_project

  def index
    @pledges = @project.pledges
  end

  def new
    @pledge = @project.pledges.new
  end

  def create
    @pledge = @project.pledges.new(pledge_params)
    if @pledge.save
      redirect_to project_pledges_path(@project),
        notice: "Thanks for pledging!"
    else
      render :new
    end
  end

private

  def pledge_params
    params.require(:pledge).permit(:name, :email, :amount, :comment)
  end

  def set_project
    @project = Project.find(params[:project_id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.accepting_pledges
  end

  def show
  	@project = Project.find(params[:id]) 	
  end

  def edit
  	@project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to @project, notice: "Project successfully updated!"
    else
      render :edit
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project, notice: "Project successfully created!"
    else
      render :new
    end 
  end

  def destroy
    @project = Project.find(params[ :id])
    @project.destroy
    redirect_to projects_url, alert: "Project successfully deleted!"
  end

  private

  def project_params
    params.require(:project).permit(:name, :description, :pledging_ends_on, :target_pledge_amount, :website, :team_leader, :image_file_name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

  def create
    if user = User.authenticate(params[:email], params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome back, #{user.name}!"
      redirect_to(session[:intended_url]) || user
      session[:intended_url] = nil
    else
      flash.now[:alert] = "Invalid email/password combination!"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "You've successfully signed out!"
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_signin, except: [:new, :create]
	before_action :require_correct_user, only: [:edit, :update, :destroy]
	def index
		@users = User.all	
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
	  @user = User.new(user_params)
	  if @user.save
	  	session[:user_id] = @user.id
	    redirect_to @user, notice: "Thanks for signing up!"
	  else
	    render :new
	  end
	end

	def edit
		@user = User.find(params[:id])	
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to @user, notice: "Account successfully updated!"
		else
			render :edit
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		session[:user_id] = nil
		redirect_to root_url, alert: "Account successfully deleted!"
	end

	private

	def user_params
	  params.require(:user).
	    permit(:name, :email, :password, :password_confirmation, :username)
	end

	def require_correct_user
		@user = User.find(params[:id])
		redirect_to root_url unless current_user?(@user)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
	def pledge_link_for(project)
	    if project.funded?
	      content_tag(:strong, "Funded!")
	    else
	      hint = content_tag(:span, "Only #{number_to_currency(project.amount_outstanding)} left!", class: 'scarcity')
	      link_to "Pledge! #{hint}".html_safe, new_project_pledge_path(project), class: 'button ok pledge'
	    end
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def format_pledging_ends_on(project)
    if project.pledging_expired?
      content_tag(:strong, 'All Done!')
    else
      distance_of_time_in_words(Date.today, project.pledging_ends_on) + " remaining"
    end
  end

  def image_for(project)
  	if project.image_file_name.blank?
  		image_tag 'placeholder.png'
  	else
  		image_tag project.image_file_name
  	end 	
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def profile_image_for(user)
    url = "https://secure.gravatar.com/avatar/#{user.gravatar_id}"
    image_tag(url, alt: user.name)
  end
end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="page-footer">
	<p>
		Copyright &copy; 2015 CrowdfunderByCatfriend
	</p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
<h1>Crowdfunder</h1>

<nav>
	<p>
		<% if current_user %>
		<%= current_user.username + ' is online' %>
		<% end %>
	</p>

</nav>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
  <nav>
    <ul>
      <li>
        <%= link_to 'All Projects', projects_path %>
      </li>
      <li>
        <%= link_to 'Add New Project', new_project_path %>
      </li>
        <p>
          <li>
      <% if current_user %>
        <%= link_to " Your Account Settings", edit_user_path(current_user) %>
        <li>
        <%= link_to 'Sign Out', session_path, method: :delete, class: 'button' %>
      </li>
      <% else %>
        <%= link_to 'Sign Up', signup_path, class: 'button' %>
        <%= link_to 'Sign In', new_session_path, class: 'button' %>
      <% end %>
  </p>
</li>


    </ul>
  </nav>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfunder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>

<div id="wrapper">

  <%= render "layouts/flashes" %>

  <div id="container">
    <%= render "layouts/sidebar" %>
    <section id="content">
      <%= yield %>
    </section>
  </div>

</div>

<%= render "layouts/footer" %>

</body>
</html>

app/views/pledges/index.html.erb
<header id="content-header">
  <h1>Pledges for <%= link_to(@project.name, @project) %></h1>
</header>

<ol id="pledges">
  <% @pledges.each do |p| %>
    <li>
      <%= mail_to(p.email, p.name) %> pledged
      <span class="amount"><%= number_to_currency(p.amount) %></span>
      (<span class="date"><%= time_ago_in_words(p.created_at) %> ago<span>)
      <p>
        &quot;<%= p.comment %>&quot;
      </p>
    </li>
  <% end %>
</ol>

app/views/pledges/new.html.erb
<header id="content-header">
  <h1>New Pledge for <%= link_to @project.name, @project %></h2>
</header>

<%= form_for([@project, @pledge]) do |f| %>
  <%= render "shared/errors", object: @pledge %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :name %>
        <%= f.text_field :name, size: 40, autofocus: true, placeholder: "Your Name" %>
      </li>
      <li class="required">
        <%= f.label :email %>
        <%= f.text_field :email, size: 40, placeholder: "Your email (will not display)" %>
      </li>
      <li class="required">
        <%= f.label :amount %>
        <%= f.select :amount, Pledge::AMOUNT_LEVELS,
                     prompt: "Pick one" %>
      </li>
      <li>
        <%= f.label :comment %>
        <%= f.text_area :comment, cols: 60, rows: 10, placeholder: "Tell us what you think about this project" %>
      </li>
    </ol>
    <p>
      <%= f.submit %>
      <%= link_to "Cancel", @project, class: 'button' %>
    </p
  </fieldset>
<% end %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <%= render "shared/errors", object: @project %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true %>
      </li>
      <li class="required">
        <%= f.label :description %>
        <%= f.text_area :description, cols: 40, rows: 7 %>
      </li>
      <li class="required">
        <%= f.label :pledging_ends_on %>
        <%= f.date_select :pledging_ends_on %>
      </li>
      <li class="required">
        <%= f.label :target_pledge_amount %>
        <%= f.number_field :target_pledge_amount %>
      </li>
      <li class="required">
        <%= f.label :website %>
        <%= f.text_field :website %>
      </li>
      <li class="required">
        <%= f.label :team_leader %>
        <%= f.text_field :team_leader %>
      </li>
      <li class="required">
        <%= f.label :image_file_name, 'Image Filename' %>
        <%= f.text_field :image_file_name, size: 30,
                         placeholder: "GIF, JPG, or PNG file name" %>
      </li>
    </ol>
    <p>
      <%= f.submit %>
      <%= link_to "Cancel", projects_path, class: 'button' %>
    </p>
  </fieldset>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project: <%= @project.name %></h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<h1><%= pluralize(@projects.size, 'Project') %></h1>

<% @projects.each do |project| %>
  <article>
    <header>
      <%= image_for(project) %>
      <h2><%= link_to(project.name, project) %></h2>
    </header>
    <p>
      <%= truncate(project.description, length: 50) %>
    </p>
    <table>
      <tr>
        <th>Target Pledge Amount:</th>
        <td><%= number_to_currency(project.target_pledge_amount) %></td>
      </tr>
      <tr>
        <th>Pledging Ends:</th>
        <td><%= format_pledging_ends_on(project) %></td>
      </tr>
          <tr>
        <th>Project Website:</th>
        <td><%= project.website %></td>
      </tr>
    </table>
  </article>
<% end %>

<%= link_to("Add New Project", new_project_path) %>

app/views/projects/new.html.erb
<h1>Create Project:</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<article id="project" class="project">
  <header>
    <%= image_for(@project) %>
    <h1><%= @project.name %></h1>
    <h2><%= format_pledging_ends_on(@project) %></h2>
  </header>
  <h2>Description</h2>
  <p>
    <%= @project.description %>
  </p>
  <h3>Target Pledge Amount</h3>
  <p>
    <%= number_to_currency(@project.target_pledge_amount) %>
  </p>
    <h3>Pledging Ends</h3>
  <p>
    <%= format_pledging_ends_on(@project) %>
  </p>
  <h3>Website</h3>
  <p>
    <%= @project.website %>
  </p>
  <h3>Team Leader</h3>
  <p>
    <%= @project.team_leader %>
  </p>
  <h3>Total Amount Pledged</h3>
  <p>
    <%= number_to_currency(@project.total_amount_pledged) %>
  </p>
    <h3>Pledges</h3>
  <p>
    <%= link_to pluralize(@project.pledges.size, "pledge"), 
                project_pledges_path(@project) %>
  </p>
  <h3>Image</h3>
  <p>
    <%= (@project.image_file_name) %>
  </p>
    <footer>
    <%= link_to "Pledge!", new_project_pledge_path(@project),
                           class: 'button ok pledge' %>
    <nav>
      <%= link_to "Edit", edit_project_path(@project), class: 'button' %>
      <%= link_to "Delete", @project,
                  class: 'button',
                  method: :delete, data: { confirm: 'Are you sure?' } %>
    </nav>
  </footer>
</article>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<section id="errors">
  <header>
    <h2>
      Oops! The <%= object.class.name.titleize.downcase %> could not be saved. 
    </h2>
    <h3>
      Please correct the following <%= pluralize(object.errors.count, "error") %>:
    </h3>
  </header>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</section>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render "shared/errors", object: @user %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :name %>
        <%= f.text_field :name, size: 40, autofocus: true %>
      </li>
      <li class="required">
        <%= f.label :email %>
        <%= f.email_field :email, size: 40 %>
      </li>
      <li class="required">
        <%= f.label :username %>
        <%= f.text_field :username, size: 40,
                                placeholder: "Alphanumeric characters only!" %>
      </li>
      <li class="required">
        <%= f.label :password %>
        <%= f.password_field :password, size: 40 %>
      </li>
      <li class="required">
        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation, size: 40 %>
      </li>
    </ol>
    <p>
      <% if @user.new_record? %>
          <%= f.submit "Create Account" %>
      <% else %>
          <%= f.submit "Update Account" %>
      <% end %>
    </p>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<header id="content-header">
  <h1>Edit Account</h1>
</header>

<%= render 'form' %>

app/views/users/index.html.erb
<header id="content-header">
  <h1><%= pluralize(@users.size, 'User') %></h1>
</header>

<ul id="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<header id="content-header">
  <h1>Sign Up</h1>
</header>

<%= render 'form' %>

app/views/users/show.html.erb
<article id="user">

  <%= profile_image_for(@user) %>
  <%= link_to current_user.name, current_user %>
  <h1><%= @user.name %></h1>
  <h2><%= mail_to(@user.email) %></h2>
  <h3>Member Since</h3>
  <p>
    <%= @user.created_at.strftime("%B %Y") %>
  </p>

</article>

<footer>
  <nav>
    <% if current_user?@user %>
      <%= link_to 'Edit Account', edit_user_path(@user), class: 'button' %>
      <%= link_to 'Delete Account', @user,
              method: :delete,
              data: { confirm: 'Are you sure you want to permanently delete your account?' } %>
    <% end %>
  </nav>
</footer>